### ISSUE TITLE
Help with installation: Error (fedora/36-cloud-base' could not be found)  ( trouble is: we are using Fedora 39 )

### ISSUE THREAD

**Issue by Rickyrivits** [tarxf/roonux#6]
ricky@fedora:~$ git clone https://github.com/tarxf/roonux.git
Cloning into 'roonux'...
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 78 (delta 36), reused 56 (delta 25), pack-reused 0
Receiving objects: 100% (78/78), 121.16 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (36/36), done.
ricky@fedora:~$ cd roonux
ricky@fedora:~/roonux$ vagrant up --provider virtualbox
bash: vagrant: command not found...
Install package 'vagrant' to provide command 'vagrant'? [N/y] y

 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 bsdtar-3.7.1-1.fc39.x86_64	Manipulate tape archives
 clevis-19-4.fc39.x86_64	Automated decryption framework
 clevis-luks-19-4.fc39.x86_64	LUKS integration for clevis
 clevis-pin-tpm2-0.5.3-2.fc39.x86_64	Clevis PIN for unlocking with TPM2 supporting Authorized Policies
 dhcpcd-10.0.5-1.fc39.x86_64	A minimalistic network configuration daemon with DHCPv4, rdisc and DHCPv6 support
 gdisk-1.0.9-6.fc39.x86_64	An fdisk-like partitioning tool for GPT disks
 guestfs-tools-1.51.6-2.fc39.x86_64	Tools to access and modify virtual machine disk images
 hexedit-1.6-4.fc39.x86_64	A hexadecimal file viewer and editor
 hivex-libs-1.3.23-12.fc39.x86_64	Library for hivex
 jose-11-8.fc39.x86_64	Tools for JSON Object Signing and Encryption (JOSE)
 libguestfs-1:1.51.9-1.fc39.x86_64	Access and modify virtual machine disk images
 libguestfs-appliance-1:1.51.9-1.fc39.x86_64	Appliance for libguestfs
 libguestfs-xfs-1:1.51.9-1.fc39.x86_64	XFS support for libguestfs
 libjose-11-8.fc39.x86_64	Library implementing JSON Object Signing and Encryption
 libldm-0.2.4-13.fc39.x86_64	A tool to manage Windows dynamic disks
 libluksmeta-9-16.fc39.x86_64	Library for storing small metadata in the LUKSv1 header
 lsscsi-0.32-8.fc39.x86_64	List SCSI devices (or hosts) and associated information
 luksmeta-9-16.fc39.x86_64	Utility for storing small metadata in the LUKSv1 header
 podman-docker-5:4.8.1-1.fc39.noarch	Emulate Docker CLI using podman
 qemu-kvm-core-2:8.1.3-1.fc39.x86_64	QEMU metapackage for KVM support
 ruby-3.2.2-181.fc39.x86_64	An interpreter of object-oriented scripting language
 ruby-bundled-gems-3.2.2-181.fc39.x86_64	Bundled gems which are part of Ruby StdLib
 ruby-default-gems-3.2.2-181.fc39.noarch	Default gems which are part of Ruby StdLib
 ruby-libs-3.2.2-181.fc39.x86_64	Libraries necessary to run Ruby
 rubygem-bcrypt_pbkdf-1.1.0-7.fc39.x86_64	OpenBSD's bcrypt_pdkfd (a variant of PBKDF2 with bcrypt-based PRF)
 rubygem-bigdecimal-3.1.3-181.fc39.x86_64	BigDecimal provides arbitrary-precision floating point decimal arithmetic
 rubygem-builder-3.2.4-9.fc39.noarch	Builders for MarkUp
 rubygem-bundler-2.4.10-181.fc39.noarch	Library and utilities to manage a Ruby application's gem dependencies
 rubygem-childprocess-4.1.0-5.fc39.noarch	A gem for controlling external programs running in the background
 rubygem-concurrent-ruby-1.1.9-4.fc39.noarch	Modern concurrency tools for Ruby
 rubygem-diffy-3.4.2-1.fc39.noarch	A convenient way to diff string in ruby
 rubygem-domain_name-0.6.20231109-1.fc39.noarch	Domain Name manipulation library for Ruby
 rubygem-ed25519-1.3.0-4.fc39.x86_64	An efficient digital signature library providing the Ed25519 algorithm
 rubygem-erubi-1.10.0-6.fc39.noarch	Small ERB Implementation
 rubygem-excon-0.100.0-1.fc39.noarch	Speed, persistence, http(s)
 rubygem-ffi-1.15.5-7.fc39.x86_64	FFI Extensions for Ruby
 rubygem-fog-core-2.3.0-1.fc39.noarch	Shared classes and tests for fog providers and services
 rubygem-fog-json-1.2.0-11.fc39.noarch	JSON parsing for fog providers
 rubygem-fog-libvirt-0.9.0-4.fc39.noarch	Module for the 'fog' gem to support libvirt
 rubygem-fog-xml-0.1.4-5.fc39.noarch	XML parsing for fog providers
 rubygem-formatador-0.2.5-16.fc39.noarch	Ruby STDOUT text formatting
 rubygem-hashicorp-checkpoint-0.1.5-12.fc39.noarch	Internal HashiCorp service to check version information
 rubygem-http-accept-2.1.1-9.fc39.noarch	Parse Accept and Accept-Language HTTP headers
 rubygem-http-cookie-1.0.5-4.fc39.noarch	Ruby library to handle HTTP Cookies based on RFC 6265
 rubygem-i18n-1.14.1-2.fc39.noarch	New wave Internationalization support for Ruby
 rubygem-io-console-0.6.0-181.fc39.x86_64	IO/Console is a simple console utilizing library
 rubygem-irb-1.6.2-181.fc39.noarch	The Interactive Ruby
 rubygem-json-2.6.3-204.fc39.x86_64	A JSON implementation in Ruby
 rubygem-listen-3.7.1-3.fc39.noarch	Listen to file modifications
 rubygem-log4r-1.1.10-20.fc39.noarch	Log4r, logging framework for ruby
 rubygem-mime-types-3.4.1-3.fc39.noarch	The mime-types library provides a library
 rubygem-mime-types-data-3.2023.0218.1-2.fc39.noarch	A registry for information about MIME media type definitions
 rubygem-multi_json-1.15.0-8.fc39.noarch	A common interface to multiple JSON libraries
 rubygem-net-scp-4.0.0-3.fc39.noarch	A pure Ruby implementation of the SCP client protocol
 rubygem-net-sftp-4.0.0-2.fc39.noarch	A pure Ruby implementation of the SFTP client protocol
 rubygem-net-ssh-7.1.0-2.fc39.noarch	Net::SSH: a pure-Ruby implementation of the SSH2 client protocol
 rubygem-netrc-0.11.0-14.fc39.noarch	Library to read and write netrc files
 rubygem-nokogiri-1.15.5-1.fc39.x86_64	An HTML, XML, SAX, and Reader parser
 rubygem-psych-5.0.1-181.fc39.x86_64	A libyaml wrapper for Ruby
 rubygem-racc-1.7.1-201.fc39.x86_64	LALR(1) parser generator
 rubygem-rb-inotify-0.10.1-8.fc39.noarch	A Ruby wrapper for Linux inotify, using FFI
 rubygem-rdoc-6.5.0-181.fc39.noarch	A tool to generate HTML and command-line documentation for Ruby projects
 rubygem-rest-client-2.1.0-12.fc39.noarch	Simple HTTP and REST client for Ruby
 rubygem-rexml-3.2.5-181.fc39.noarch	An XML toolkit for Ruby
 rubygem-ruby-libvirt-0.7.1-19.fc39.x86_64	Ruby bindings for LIBVIRT
 rubygem-rubyzip-2.3.2-6.fc39.noarch	A ruby module for reading and writing zip files
 rubygem-xml-simple-1.1.9-6.fc39.noarch	A simple API for XML processing
 rubygems-3.4.10-181.fc39.noarch	The Ruby standard for packaging ruby libraries
 rubypick-1.1.1-19.fc39.noarch	Stub to allow choosing Ruby runtime
 scrub-2.6.1-7.fc39.x86_64	Disk scrubbing program
 supermin-5.3.3-15.fc39.x86_64	Tool for creating supermin appliances
 syslinux-6.04-0.25.fc39.x86_64	Simple kernel loader which boots from a FAT filesystem
 syslinux-extlinux-6.04-0.25.fc39.x86_64	The EXTLINUX bootloader, for booting the local system.
 syslinux-extlinux-nonlinux-6.04-0.25.fc39.noarch	The parts of the EXTLINUX bootloader which aren't run from linux.
 syslinux-nonlinux-6.04-0.25.fc39.noarch	SYSLINUX modules which aren't run from linux.
 vagrant-2.3.4-3.fc39.noarch	Build and distribute virtualized development environments
 vagrant-libvirt-0.11.2-2.fc39.noarch	libvirt provider for Vagrant
 zerofree-1.1.1-12.fc39.x86_64	Utility to force unused ext2/3/4 inodes and blocks to zero
 zstd-1.5.5-4.fc39.x86_64	Zstd compression library
Proceed with changes? [N/y] y

 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'fedora/36-cloud-base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 36-20220504.1
==> default: Loading metadata for box 'fedora/36-cloud-base'
    default: URL: https://vagrantcloud.com/fedora/36-cloud-base
==> default: Adding box 'fedora/36-cloud-base' (v36-20220504.1) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/fedora/boxes/36-cloud-base/versions/36-20220504.1/providers/virtualbox/unknown/vagrant.box
Download redirected to host: download.fedoraproject.org
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404

ricky@fedora:~/roonux$

**Comment by tarxf** [comment]
Sorry, I'm just seeing your issue now, are you still experiencing the problem? I also just updated the fedora distro to 39, in case you want to retry the instructions. I tested it and it booted okay.

**Comment by tarxf** [comment]
I have updated this guide to run with fedora cloud 41 and I tested it again. If you find any errors, please open another ticket.
